const express = require('express');
const router = express.Router();

const { signin } = require('../controllers/signin/signin.js');
const { signup } = require('../controllers/signup/signup.js');
const { table } = require('../controllers/table/table.js');
const { tableData } = require('../controllers/tableData/tableData.js');
const { requestData } = require('../controllers/requestData/requestData.js');
const { approve } = require('../controllers/approve/approve.js');
const { reject } = require('../controllers/reject/reject.js');
const { fetchChangeTrackerData } = require('../controllers/changeTrackerData/fetchChangeTrackerData.js');
const { columnStatusPermission } = require('../controllers/columnStatusPermission/columnStatusPermission.js');
const { fetchColumn } = require('../controllers/fetchColumn/fetchColumn.js');
const { fetchColumnStatus } = require('../controllers/fetchColumnStatus/fetchcolumnstatus.js');
const { updateColumnDropDown } = require('../controllers/updateColumnDropdown/updateColumnDropDown.js');
const { fetchColumnDropDown } = require('../controllers/fetchColumnDropdown/fetchColumnDropDown.js');
const { fetchDropDownOptions } = require('../controllers/fetchDropDownOptions/fetchDropDownOptions.js');
const { allApprove } = require('../controllers/approveAll/allApprove.js');
const { allReject } = require('../controllers/allReject/allReject.js');
const { sendOTP } = require('../controllers/sendOTP/sendOTP.js');
const { verifyOTP } = require('../controllers/verifyOTP/verifyOTP.js');
const { addGroup } = require('../controllers/tablesGroup/tableGroup.js');
const { addTable } = require('../controllers/tablesGroup/tableGroup.js');
const { getGroupList } = require('../controllers/getGroupList/getGroupList.js');
const { removeGroup } = require('../controllers/removeGroup/removeGroup.js');
const { removeTable } = require('../controllers/removeTable/removeTable.js');
const { getAllCheckerRequest } = require('../controllers/getAllCheckerRequest/getAllCheckerRequest.js');
const { addRow } = require('../controllers/addRow/addRow.js');
const { fetchRowRequest } = require('../controllers/fetchRowRequest/fetchRowRequest.js');
const { acceptRow } = require('../controllers/approveRow/acceptRow.js');
const { rejectRow } = require('../controllers/rejectRow/rejectRow.js');
const { rejectAllRow } = require('../controllers/rejectAllRow/rejectAllRow.js');
const { acceptAllRow } = require('../controllers/approveAllRow/acceptAllRow.js');
const { isActive } = require('../controllers/isActive/isActive.js');


router.post('/signin', signin);
router.post('/signup', signup);
router.get('/table', table);
router.get('/tableData/:name', tableData);
router.post('/requestdata', requestData);
router.post('/approve', approve);
router.post('/reject', reject);
router.get('/fetchchangetrackerdata', fetchChangeTrackerData);
router.post('/columnstatuspermission', columnStatusPermission);
router.post('/fetchcolumn', fetchColumn);
router.post('/fetchcolumnstatus', fetchColumnStatus);
router.post('/updatecolumndropdown', updateColumnDropDown);
router.post('/fetchcolumndropdown', fetchColumnDropDown);
router.post('/fetchdropdownoptions', fetchDropDownOptions);
router.post('/approveall', allApprove);
router.post('/rejectall', allReject);
router.post('/sendotp', sendOTP);
router.post('/verifyotp', verifyOTP);
router.post('/addgroup', addGroup);
router.post('/addtable', addTable);
router.get('/getgrouplist', getGroupList);
router.post('/removegroup', removeGroup);
router.post('/removetable', removeTable);
router.post('/getallcheckerrequest', getAllCheckerRequest);
router.post('/addrow', addRow);
router.post('/fetchrowrequest', fetchRowRequest);
router.post('/acceptrow', acceptRow);
router.post('/rejectrow', rejectRow);
router.post('/rejectallrow', rejectAllRow);
router.post('/isactive', isActive);

module.exports = router;